# Much of this setup is borrowed or inspired from the travis.yml files
# of the param, holoviews and related packages.

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  - GSFORGE_DEMO_DATA="${HOME}/GSForge_demo_data"


language: python

python:
  - "3.8"


services:
  - docker


stages:
  - name: website_dev
    if: (tag =~ ^v(\d+|\.)+[a-z]+\d*$) OR (commit_message =~ travis_dev)
  - name: pip_dev_package
    if: (tag =~ ^v(\d+|\.)+[a-z]+\d*$) OR (commit_message =~ travis_dev)
  - name: build_dev_dockerfiles
    if: (tag =~ ^v(\d+|\.)+[a-z]+\d*$) OR (commit_message =~ travis_dev)

  - name: website_release
    if: tag =~ ^v(\d+|\.)+[^a-z]\d+$ OR tag = website
  - name: pip_package
    if: tag =~ ^v(\d+|\.)+[^a-z]\d+$
  - name: build_dockerfiles
    if: tag =~ ^v(\d+|\.)+[^a-z]\d+$



jobs:
  include:

    - stage: website_release
      install:
        - sudo apt-get install graphviz
        - pip install osfclient
        - pip install .[docs]
      script:
        - osf -p rbhfz clone "$GSFORGE_DEMO_DATA"
        - mkdir doc/Reference_Manual
        - nbsite_generate_modules.py GSForge -d ./doc/Reference_Manual -n GSForge
        - nbsite generate-rst --org SystemsGenetics --project-name GSForge
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          on:
            branch: master

    - stage: website_dev
      install:
        - sudo apt-get install graphviz
        - pip install osfclient
        - pip install .[docs]
      script:
        - osf -p rbhfz clone "$GSFORGE_DEMO_DATA"
        - mkdir doc/Reference_Manual
        - nbsite_generate_modules.py GSForge -d ./doc/Reference_Manual -n GSForge
        - nbsite generate-rst --org SystemsGenetics --project-name GSForge
        - nbsite build --what=html --output=builtdocs
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./builtdocs
          target_branch: gh-pages
          github_token: $GITHUB_TOKEN
          repo: SystemsGenetics/GSForgeDev
          on:
            all_branches: true

    - stage: build_dockerfiles
      env:
        -GSFORGE_IMAGE_TAG="${TRAVS_TAG}"
      install: skip
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gsforge_interactive:latest
        - docker push systemsgenetics/gsforge_workflow:latest

    - stage: build_dev_dockerfiles
      env:
        -GSFORGE_IMAGE_TAG="dev"
      install: skip
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push systemsgenetics/gsforge_interactive:dev
        - docker push systemsgenetics/gsforge_workflow:dev

    - stage: pip_dev_package
      install: skip
      script:
        - pip install .
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
        on:
          tags: true
        user: $TESTPYPI_USER
        password: $TESTPYPI_PWD

    - stage: pip_package
      install: skip
      script:
        - pip install .
      deploy:
        provider: pypi
        distributions: "sdist bdist_wheel"
        on:
          tags: true
        user: $PYPI_USER
        password: $PYPI_PWD
