version: '3.3'

services:
  interactive:
    image: systemsgenetics/gsforge_interactive:${GSFORGE_IMAGE_TAG:-dev}
    build:
      context: .
      dockerfile: './docker/notebook/Dockerfile'

  workflow:
    image: systemsgenetics/gsforge_workflow:${GSFORGE_IMAGE_TAG:-dev}
    build:
      context: .
      dockerfile: './docker/workflow/Dockerfile'
